# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']
  url: '%env(MAILER_URL)%'
  # send all emails to a specific address
  delivery_addresses: ['natyv225@gmail.com']
  sender_address: '%env(resolve:MAILER_FROM_ADDRESS)%'



